
# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-netlify-toml-file
[build]
  publish = "_site"
  command = "npm run build"
  environment = { NODE_VERSION = "18.16.0" }

# https://www.netlify.com/products/dev/
# https://github.com/netlify/cli/blob/main/docs/netlify-dev.md
[dev]
  command = "deno task dev" # Command to start your dev server
  targetPort = 4000 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser

  # publish = "dist" # The path to your static content folder
  # jwtSecret = "secret" # The secret used to verify tokens for JWT based redirects
  # jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
  # envFiles = [".env.development.local", ".env.local", ".env.development", ".env"] # The env files to use, ordered by priority (left - highest, right - lowest)
  # to start an https server instead of an http one, configure a certificate and key files
  # [dev.https]
  #   certFile = "cert.pem" # path to the certificate file
  #   keyFile = "key.pem" # path to the private key file
