# https://deno.com/deploy
# https://github.com/denoland/deployctl/tree/main/action
name: Deploy to deno.dev

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: picture-gallery # the name of the project on Deno Deploy
          entrypoint: server.js # the entrypoint to deploy

          # The library folder contains large WebAssembly files that are only used locally.
          exclude: library
